
language: c
install: test -e .travis-ocaml.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-ocaml.sh
env:
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.09
  - OCAML_VERSION=4.10
  - OCAML_VERSION=4.11
  - OCAML_VERSION=4.12
os:
  - linux
arch:
  - amd64
